### PR TITLE
fix: show text input field for non-enumerable NFT

### LINKED ISSUE #222: Deposit: cannot deposit non-enumerable NFTs
If token doesn't implement [ERC721Enumerable](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721Enumerable.sol), Bridge UI just shows "No tokens" select box. There is no way to put in token id directly

### PR DESCRIPTION
**Pull request by troggy**
Because there is no other way to enter token id for those.

Resolves #222

### CODE REVIEW

**Comment by troggy** [comment]
bridge-nft

File: src/components/amountInput.tsx [hunk 1]
```diff
@@ -104,10 +104,10 @@ export default class AmountInput extends React.Component<
   public render() {
     const { onColorChange, value, width = 250, plasma, ...rest } = this.props;
     const balance = plasma ? this.token.plasmaBalance : this.token.balance;
-
+    const enumerableNft = this.token.isNft && balance && balance[0];
```
Comment (sunify) [inline src/components/amountInput.tsx]: `Array.isArray(balance)`?

Comment (troggy) [reply src/components/amountInput.tsx]: so check for `balance[0]` actually distringuish between enumerable and non-enumerable here. For the latter it will be undefined. Yet both are arrays

**Comment by troggy** [comment]
merged optimistically
